//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxAppBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration
    {
        public int DeclarationId { get; set; }
        public string DeclarationName { get; set; }
        public string DeclarationYear { get; set; }
        public string DeclarationNote { get; set; }
    }
}
